Reservation, Customer, VehicleType, Vehicle Database Methods
azizsonawalla/CPSC304-SuperRent-Car-Rental-System pull request #9
Opened 2019-11-21 06:50 UTC by ubcgchen

- Implemented and tested all methods for above entities in the Database class
- VehicleStatus enumeration
- Not NULL Statements in Vehicle table

2019-11-22 03:17 UTC, hashmi97 requested changes

2019-11-22 03:17 UTC, hashmi97 commented on src/main/java/model/Database.java
> +        rs.next();
Why are you doing this instead of just using the UPDATE VEHICLE query?

2019-11-22 03:17 UTC, hashmi97 commented on src/main/java/model/Database.java
> +        PreparedStatement ps = conn.prepareStatement("SELECT * FROM Vehicle WHERE vLicense = '" + v.vlicense + "'");
We should add the Query to the Query class and reference it here, rather than have queries all over the project

2019-11-22 03:18 UTC, hashmi97 commented on src/main/java/model/Database.java
> +        rs.next();
nvm, I get it now, 
Just make sure those SQL stamtnets are all stored in the Query Class, I am calling them "GET_CARD, GET_BRANCH, GET_RENT, etc"

2019-11-22 03:30 UTC, hashmi97 commented on src/main/java/model/Database.java
> +        rs.next();
Same goes for the other SQL Queries in getReservationMatching .. etc

2019-11-23 21:34 UTC, azizsonawalla approved these changes

2019-11-23 21:35 UTC, hashmi97 approved these changes

2019-11-23 21:35 UTC, merged